name: Terraform CI (Automatyczna Walidacja)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform-validate:
    name: 'Terraform Format & Validate'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init -backend=false

    - name: Terraform Format
      run: terraform fmt -check
      continue-on-error: true

    - name: Generate dummy SSH key for validation
      run: |
        mkdir -p ~/.ssh
        ssh-keygen -t rsa -b 2048 -N "" -f ~/.ssh/id_rsa

    - name: Terraform Validate
      run: terraform validate

    # ---- NOWY KROK DLA ANSIBLE ----
    - name: Sprawdzenie skladni Ansible
      run: ansible-playbook --syntax-check playbook.yml
