name: Terraform CI (Automatyczna Walidacja)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform-validate:
    name: 'Terraform Format & Validate'
    runs-on: ubuntu-latest

    steps:
    # 1. Pobranie Twojego kodu z repozytorium
    - name: Checkout Repo
      uses: actions/checkout@v3

    # 2. Instalacja środowiska Terraform na serwerze GitHuba
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # 3. Inicjalizacja (bez łączenia z chmurą)
    - name: Terraform Init
      run: terraform init -backend=false

    # 4. Sprawdzenie, czy kod jest ładnie sformatowany
    - name: Terraform Format
      run: terraform fmt -check
      continue-on-error: true

    # 5. Sprawdzenie poprawności składni (walidacja)
    - name: Terraform Validate
      run: terraform validate
